CSS:
  beautifiers:
    - Prettier
    - Pretty Diff
    - JS-Beautify
  indent_size: 2
  wrap_line_length: 0
HTML:
  beautifiers:
    - Pretty Diff
    - JS-Beautify
  indent_size: 2
  quotes: double
  wrap_line_length: 0
JSON:
  beautifiers:
    - Prettier
    - Pretty Diff
    - JS-Beautify
  indent_size: 2
  quotes: double
  wrap_line_length: 0
JavaScript:
  beautifiers:
    - Prettier
    - Pretty Diff
    - JS-Beautify
    - ESLint
  indent_size: 2
  quotes: single
  wrap_line_length: 0
Markdown:
  beautifiers:
    - Prettier
  indent_size: 2
SCSS:
  beautifiers:
    - Prettier
    - Pretty Diff
  indent_size: 2
  quotes: double
  wrap_line_length: 0
SVG:
  beautifiers:
    - Pretty Diff
  indent_size: 2
